title: Jose Hernández
author: Jose Hernández
twitter: josehernandz
domain: http://josehernandez.xyz/

lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    span:
      line_numbers: false
      wrap: false
    block:
      line_numbers: true

excerpt_separator: <!--more-->

paginate: 6

collections:
  - works

gems:
  - jekyll-sitemap